repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(web-frontend/\.nuxt/|web-frontend/dist/|web-frontend/\.output/)
      - id: end-of-file-fixer
        exclude: ^(web-frontend/\.nuxt/|web-frontend/dist/|web-frontend/\.output/)
      - id: check-yaml
        exclude: ^(web-frontend/\.nuxt/|web-frontend/dist/|web-frontend/\.output/)
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [ --fix, --config, backend/pyproject.toml ]
      - id: ruff-format
        args: [ --config, backend/pyproject.toml ]

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: web-frontend/node_modules/.bin/eslint --config eslint.config.mjs --fix
        language: system
        files: \.(js|jsx|ts|tsx|vue|mjs)$
        exclude: ^(web-frontend/\.nuxt/|web-frontend/dist/|web-frontend/\.output/)

      - id: stylelint
        name: stylelint
        entry: web-frontend/node_modules/.bin/stylelint --config web-frontend/stylelint.config.mjs --fix
        language: system
        files: \.scss$
        exclude: ^(web-frontend/\.nuxt/|web-frontend/dist/|web-frontend/\.output/)

      - id: prettier
        name: prettier
        entry: web-frontend/node_modules/.bin/prettier --write
        language: system
        files: \.(js|jsx|ts|tsx|vue|css|scss|json|md|html)$
        exclude: ^(web-frontend/\.nuxt/|web-frontend/dist/|web-frontend/\.output/)
