# Generated by Django 5.0.9 on 2025-03-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0054_simplecontainerelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="columnelement",
            name="column_layout",
            field=models.CharField(
                choices=[("auto", "Auto"), ("flexi", "Flexi"), ("manual", "Manual")],
                db_default="auto",
                default="auto",
                help_text="Behaviour for each column.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="columnelement",
            name="column_weights",
            field=models.JSONField(
                db_default=[],
                default=list,
                help_text="The weight associated with each column.",
            ),
        ),
    ]
