# Generated by Django 5.0.9 on 2025-04-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0056_ratingelement_ratinginputelement"),
    ]

    operations = [
        migrations.AddField(
            model_name="footerelement",
            name="behaviour",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("fixed", "Fixed"),
                    ("sticky", "Sticky"),
                ],
                default="normal",
                db_default="normal",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="headerelement",
            name="behaviour",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("fixed", "Fixed"),
                    ("sticky", "Sticky"),
                ],
                default="normal",
                db_default="normal",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="simplecontainerelement",
            name="behaviour",
            field=models.CharField(
                choices=[("normal", "Normal"), ("sticky", "Sticky")],
                default="normal",
                db_default="normal",
                max_length=15,
            ),
        ),
    ]
