# Generated by Django 5.2.11 on 2026-02-11 15:28

from collections import defaultdict

from django.db import migrations, models, transaction
from django.db.models import Exists, OuterRef

from baserow.contrib.builder.compat.graph_migrator import PageGraphMigrator
from baserow.core.utils import Progress, grouper


def forward(apps, schema_editor):
    Page = apps.get_model("builder", "Page")
    Element = apps.get_model("builder", "element")

    # Prefetch all qualifying page IDs (~150K integers, ~4MB) rather than using
    # .iterator(), which opens a server-side cursor that keeps an implicit
    # transaction open for its lifetime. That transaction would accumulate ROW
    # EXCLUSIVE locks on every page processed, blocking concurrent writes to
    # those rows for the full duration of the migration.
    page_ids = list(
        Page.objects.filter(
            Exists(Element.objects.filter(page_id=OuterRef("pk")))
        )
        .values_list("id", flat=True)
        .order_by("id")
    )

    progress = Progress(len(page_ids))
    progress.register_updated_event(
        lambda pct, _: print(f"\r  Migrating pages... {pct}%", end="", flush=True)
    )

    for chunk_ids in grouper(500, iter(page_ids)):
        chunk_ids = list(chunk_ids)
        with transaction.atomic():
            elements_by_page = defaultdict(list)
            for el in Element.objects.filter(page_id__in=chunk_ids).values(
                "id", "order", "parent_element_id", "place_in_container", "page_id"
            ):
                el["place_in_container"] = el["place_in_container"] or ""
                elements_by_page[el["page_id"]].append(el)

            pages_to_update = []
            for page_id in chunk_ids:
                page = Page(pk=page_id)
                page.graph = PageGraphMigrator(elements_by_page[page_id]).to_graph()
                pages_to_update.append(page)

            Page.objects.bulk_update(pages_to_update, ["graph"])

        progress.increment(by=len(chunk_ids))

    print()


def reverse(apps, schema_editor):
    Page = apps.get_model("builder", "Page")
    Page.objects.update(graph={})


class Migration(migrations.Migration):

    # Must be False at the class level — RunPython(atomic=False) alone is not enough.
    # With atomic=True (default), the AddField's ACCESS EXCLUSIVE lock on `builder_page`
    # is held for the entire transaction, blocking all reads and writes until the
    # migration completes. Setting this here ensures AddField commits immediately
    # so the lock is released before the data migration begins.
    atomic = False

    dependencies = [
        ("builder", "0068_alter_page_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="graph",
            field=models.JSONField(
                default=dict,
                db_default={},
                help_text="A JSON serialized graph containing the points and edges.",
            ),
        ),
        migrations.RunPython(forward, reverse),
        migrations.AlterModelOptions(
            name="element",
            options={"ordering": ("id",)},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name="element",
                    old_name="order",
                    new_name="compat_order",
                ),
                migrations.RenameField(
                    model_name="element",
                    old_name="place_in_container",
                    new_name="compat_place_in_container",
                ),
                migrations.RenameField(
                    model_name="element",
                    old_name="parent_element",
                    new_name="compat_parent_element",
                ),
                migrations.AlterField(
                    model_name="element",
                    name="compat_order",
                    field=models.DecimalField(
                        db_column="order",
                        decimal_places=20,
                        default=1,
                        editable=False,
                        help_text="Lowest first.",
                        max_digits=40,
                    ),
                ),
                migrations.AlterField(
                    model_name="element",
                    name="compat_parent_element",
                    field=models.ForeignKey(
                        db_column="parent_element_id",
                        default=None,
                        help_text="The parent element, if inside a container.",
                        null=True,
                        on_delete=models.CASCADE,
                        related_name="compat_children",
                        to="builder.element",
                    ),
                ),
                migrations.AlterField(
                    model_name="element",
                    name="compat_place_in_container",
                    field=models.CharField(
                        blank=True,
                        db_column="place_in_container",
                        default=None,
                        help_text="The place in the container.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            # There are no database operations, we're only changing the
            # names of the fields in the model, the column names remain.
            database_operations=[],
        ),
    ]
