# Generated by Django 5.2.13 on 2026-05-08 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0029_alter_automationworkflowhistory_original_workflow'),
        ('core', '0114_alter_workspaceinvitation_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAutomationUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('dispatch_count', models.IntegerField(db_default=0, default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'period')},
            },
        ),
    ]
