# Generated by Django 5.2.13 on 2026-05-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0029_alter_automationworkflow_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationworkflow',
            name='graph',
            field=models.JSONField(db_default={}, default=dict, help_text='A JSON serialized graph containing the points and edges.'),
        ),
    ]
