# Generated by Django 5.2.11 on 2026-02-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0030_workflow_graph_db_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationworkflow',
            name='graph',
            field=models.JSONField(db_default={}, default=dict, help_text='A JSON serialized graph containing the points and edges.'),
        ),
    ]
